config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  
  get 'users/list'
  get 'messages/list'

  namespace :api do
    match 'subscriptions/convert_currency', to: 'subscriptions#convert_currency', via: :post
    match 'subscriptions/create', to: 'subscriptions#create', via: :post
    resources :messages, :users, except: [:new, :edit]
  end

  # namespace path_helper hackery!
  get '/api/messages/:id', to: 'messages#show', as: :message
  get '/api/users/:id', to: 'users#show', as: :user

  get 'plans', to: 'subscriptions#plans', as: :plans
  get 'plan/:id/subscribe', to: 'subscriptions#new', as: :new_subscription
  get 'plan/:id/upgrade', to: 'subscriptions#upgrade', as: :upgrade_subscription
  get 'plan/:id/deactivate', to: 'subscriptions#deactivate', as: :deactivate_subscription
  get 'plan/:id/reactivate', to: 'subscriptions#reactivate', as: :reactivate_subscription
  get 'plan/:id/unsubscribe', to: 'subscriptions#destroy', as: :destroy_subscription

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :messages
	has_one :subscription

	validates_presence_of :email

	#Remove deactivated subscriptions above 24 hours.
	def clean_subscriptions
	  if @subscription = self.subscription
	  	unless @subscription.active?
	  	  recatch_time = ((Time.now - @subscription.deactivated_at) / 1.hour).round
	  	  if recatch_time > 24 
	  	  	@subscription.remove
	  	  end
	  	end
	  end
	end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  protect_from_forgery with: :null_session
  private

  def user_params
  	params[:user][:birth_date] = Date.strptime(params[:user][:birth_date], "%m/%d/%Y")
    params_filtered = params.require(:user).permit(:name, :gender, :country, :birth_date, :email, :password, :password_confirmation)
  end

  def query_params
    params.permit(:name, :gender, :country, :birth_date, :email, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def list
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_create_form.html.erb
<%= form_tag("/api/users.json", method: "post", id: "add_user_form") do %>
  <%= label_tag(:name, "Email:") %>
  <%= text_field_tag("email") %><br />
  <%= label_tag(:name, "User Name:") %>
  <%= text_field_tag("name") %><br />
  <%= label_tag(:country, "Country:") %>
  <%= select_tag 'country', options_for_select([["Canada", "Canada"], ["US", "US"]]) %><br />
  <%= label_tag(:gender, "Gender:") %>
  <%= select_tag 'gender', options_for_select([["Male", "Male"], ["Female", "Female"]]) %><br />
  <%= label_tag(:birth_date, "Birth Date:") %>
  <%= text_field_tag("birth_date", nil, :data => {:provide => 'datepicker' }, :style => "z-index: 9999 !important;") %><br />
  <%= label_tag(:password, "Password") %>
  <%= password_field_tag 'password' %><br />
  <%= label_tag(:password_confirmation, "Password Confirmation") %>
  <%= password_field_tag 'password_confirmation' %><br />
  <%= submit_tag("Add", id: "submit_user") %>
<% end %>

app/views/users/_user_list.html.erb
<div>
	 <table class="table table-striped table-condensed">
	<thead>
		<tr>
		    <th>Email</th>
			<th>Name</th>
			<th>Gender</th>
			<th>Country</th>
			<th>Age</th>
		</tr>
	</thead>
	<tbody id="user_list">
		<% User.all.each do |user| %>
		  <tr>
		      <td><%= link_to "#{user.id}. #{user.email}", messages_list_path(user_id: user.id) %></td>
			   <td><%= link_to "#{user.name}", messages_list_path(user_id: user.id) %></td>
			   <td><%= user.gender %></td>
			   <td><%= user.country %></td>
			   <td><%= Date.today.year - user.birth_date.to_date.year rescue nil %></td>
		  </tr>
		<% end %>
	</tbody>
	</table>
</div>

app/views/users/list.html.erb
<% content_for :title do %>Users<% end %>
<h3>Here is the user list.  Please click on one to see messages.</h3>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Create User
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create User</h4>
      </div>
      <div class="modal-body">
        <%= render "user_create_form" %>
      </div>
      <div class="modal-footer">
        <button type="button" id="user_close" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<br/>
<%= render 'user_list' %>