config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  
  get 'users/list'
  get 'messages/list'

  namespace :api do
    match 'subscriptions/convert_currency', to: 'subscriptions#convert_currency', via: :post
    match 'subscriptions/create', to: 'subscriptions#create', via: :post
    resources :messages, :users, except: [:new, :edit]
  end

  # namespace path_helper hackery!
  get '/api/messages/:id', to: 'messages#show', as: :message
  get '/api/users/:id', to: 'users#show', as: :user

  get 'plans', to: 'subscriptions#plans', as: :plans
  get 'plan/:id/subscribe', to: 'subscriptions#new', as: :new_subscription
  get 'plan/:id/upgrade', to: 'subscriptions#upgrade', as: :upgrade_subscription
  get 'plan/:id/deactivate', to: 'subscriptions#deactivate', as: :deactivate_subscription
  get 'plan/:id/reactivate', to: 'subscriptions#reactivate', as: :reactivate_subscription
  get 'plan/:id/unsubscribe', to: 'subscriptions#destroy', as: :destroy_subscription

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<br />
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Users', users_list_path %></li>
<!--<li><%= link_to 'Messages', main_app.messages_list_path %></li>-->
<li><%= link_to 'Subscription', plans_path %></li>
<li><%= link_to 'About', page_path('about') %></li>
<% unless user_signed_in? %>
	<li><%= link_to 'Sign In', new_user_session_path %></li>
	<li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% else %>
   <li><%= link_to 'Logout', destroy_user_session_path %></li>
<% end %>
<li><%= link_to current_user.email, "#" if current_user%></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>